language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.1.1/pandoc-2.1.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.1.1-1-amd64.deb
  - pandoc -v
install:
  - pip install coveralls
script:
  - python setup.py build_ext -i
  - python -m compileall -f .
  - coverage run --source=pandoc_latex_environment setup.py test
after_success:
  - coveralls
